### ISSUE TITLE
issue in month format

### ISSUE THREAD

**Issue by j209** [alborzapex/Oracle-APEX-Persian-Date-Picker#1]
Hi
thanks a lot for your work.

after install and config the plug in i have this issue:

![image](https://user-images.githubusercontent.com/18129232/153748310-4ab7ccfd-7aad-41da-ba76-05d1e976803c.png)

**Comment by alborzapex** [comment]
سلام بر شما.
After installing the plugin, you need to select the page item type correctly.
Please refer to the following address:
https://alborzapex.com/product/%d8%aa%d9%82%d9%88%db%8c%d9%85-%d8%b4%d9%85%d8%b3%db%8c-%d8%a7%d9%88%d8%b1%d8%a7%da%a9%d9%84-%d8%a7%d9%be%da%a9%d8%b3/

**Comment by j209** [comment]
درود بر شما.بعد از اتجام تمامی تنظیمات با خطای زیر هنگام ایجاد یا ویرایش رکورد  مواجه میشویم

![image](https://user-images.githubusercontent.com/18129232/153767462-83b1ccfa-1c2b-4e02-985a-ba57c4b308a2.png)

**Comment by alborzapex** [comment]
با سلام
در آدرس مربوط به Comment قبل، انتهای صفحه دو لینک زیر وجود دارد  که نحوه تنظیم  تاریخ شمسی و فرمت تاریخ در APEX توضیح داده شده.

Please refer to the following addresses to learn how to set the persian date and date format in Oracle APEX:
https://alborzapex.com/%d8%aa%d9%86%d8%b8%db%8c%d9%85-%d8%aa%d8%a7%d8%b1%db%8c%d8%ae-%d9%81%d8%a7%d8%b1%d8%b3%db%8c-%d8%af%d8%b1-apex/
https://alborzapex.com/%d8%aa%d9%86%d8%b8%db%8c%d9%85-%d9%81%d8%b1%d9%85%d8%aa-%d8%aa%d8%a7%d8%b1%db%8c%d8%ae-%d8%af%d8%b1-apex/

**Comment by j209** [comment]
با درود.تمامی تنظیمات طبق دستورالعمل صورت گرفته است.ولی خطا همچنان وجود دارد

![image](https://user-images.githubusercontent.com/18129232/153824516-f6bf1953-0cf3-49cb-ae53-450518ad7587.png)

![image](https://user-images.githubusercontent.com/18129232/153824659-a50ffbfa-6e19-4921-8bf9-ec7798514162.png)

![image](https://user-images.githubusercontent.com/18129232/153824864-902a72cf-a41f-485b-a20b-52b241a9152c.png)

**Comment by alborzapex** [comment]
با سلام
خطای شما به این دلیل هست که یک متغیر از نوع تاریخ و یا  ستونی از جدول با نوع تاریخ رو با یک رشته مقداردهی می کنید.
برای رفع مشکل از کد زیر در زمان پاس دادن مقدار استفاده کنید:
TO_DATE(:P1_ALBORZ_APEX_DTP, 'YYYY/MM/DD')
--TO_DATE('1400/11/25', 'YYYY/MM/DD')
وقتی با تاریخ شمسی کار می کنید، در صورتی که  NLS_CALENDAR=PERSIAN رو تنظیم نکرده باشید نیاز هست دستور فوق رو به صورت زیر بنویسید: (البته شما این کار رو انجام دادید)
TO_DATE(:P1_ALBORZ_APEX_DTP, 'YYYY/MM/DD', 'NLS_CALENDAR=PERSIAN')
--TO_DATE('1400/11/25', 'YYYY/MM/DD', 'NLS_CALENDAR=PERSIAN')

**Comment by j209** [comment]
اگر کد را به این صورت وارد کنیم مشکل حل میشود:


BEGIN
EXECUTE immediate 'ALTER SESSION SET NLS_CALENDAR=PERSIAN';
EXECUTE immediate 'ALTER SESSION SET NLS_DATE_FORMAT=''yyyy/mm/dd'' ';
END;

سپاس
